name: beepay
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  page_transition: ^2.1.0
  animated_splash_screen: ^1.3.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  local_auth: ^2.1.8
  device_info_plus: ^11.5.0
  flutter_dotenv: ^5.2.1
  country_code_picker: ^3.2.0
  flutter_pdfview: ^1.4.0
  pin_code_fields: ^8.0.1
  flutter_countdown_timer: ^4.1.0
  url_launcher: ^6.3.0
  fluttertoast: ^8.2.5
  http: ^1.5.0
  phone_numbers_parser: ^9.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/iconos/
    - assets/bottom/
    - assets/.env

  fonts:
    - family: ConfigRounded1
      fonts:
        - asset: "assets/config-rounded/Config Rounded Thin.otf"
          weight: 100
        - asset: "assets/config-rounded/Config Rounded Thin Italic.otf"
          weight: 100
          style: italic

        - asset: "assets/config-rounded/Config Rounded Extralight.otf"
          weight: 200
        - asset: "assets/config-rounded/Config Rounded Extralight Italic.otf"
          weight: 200
          style: italic

        - asset: "assets/config-rounded/Config Rounded Light.otf"
          weight: 300
        - asset: "assets/config-rounded/Config Rounded Light Italic.otf"
          weight: 300
          style: italic

        - asset: "assets/config-rounded/Config Rounded Regular.otf"
          weight: 400
        - asset: "assets/config-rounded/Config Rounded Italic.otf"
          weight: 400
          style: italic

        - asset: "assets/config-rounded/Config Rounded Medium.otf"
          weight: 500
        - asset: "assets/config-rounded/Config Rounded Medium Italic.otf"
          weight: 500
          style: italic

        - asset: "assets/config-rounded/Config Rounded Semibold.otf"
          weight: 600
        - asset: "assets/config-rounded/Config Rounded Semibold Italic.otf"
          weight: 600
          style: italic

        - asset: "assets/config-rounded/Config Rounded Bold.otf"
          weight: 700
        - asset: "assets/config-rounded/Config Rounded Bold Italic.otf"
          weight: 700
          style: italic

        - asset: "assets/config-rounded/Config Rounded Extrabold.otf"
          weight: 800
        - asset: "assets/config-rounded/Config Rounded Extrabold Italic.otf"
          weight: 800
          style: italic

        - asset: "assets/config-rounded/Config Rounded Black.otf"
          weight: 900
        - asset: "assets/config-rounded/Config Rounded Black Italic.otf"
          weight: 900
          style: italic

        # (Opcional) variantes "Text"
        - asset: "assets/config-rounded/Config Rounded Text.otf"
          weight: 400
        - asset: "assets/config-rounded/Config Rounded Text Italic.otf"
          weight: 400
          style: italic
